version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - DB_VOLUME:/var/lib/postgresql/data/pgdata
    networks:
      agent_network:
        aliases:
          - ${DB_HOST}
      traefik_public:
        aliases:
          - ${DB_HOST}

  odoo:
    image: odoo:16.0-20250311
    depends_on:
      - db
    volumes:
      - ODOO_VOLUME_NAME:/var/lib/odoo
      - ODOO_CONFIG_VOLUME_NAME:/etc/odoo
      - ODOO_ADDONS_VOLUME_NAME:/mnt/extra-addons
      - ODOO_ENTERPRISE_ADDONS_VOLUME_NAME:/mnt/enterprise-addons
      - INIT_SCRIPT_VOLUME:/init-script
      - INIT_DB_SQL_VOLUME:/init-db
    user: root
    entrypoint: ["/bin/sh", "-c", "cp /init-script/init-script.sh /tmp/init-script.sh && chmod +x /tmp/init-script.sh && /tmp/init-script.sh"]
    networks:
      - agent_network
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.odoo.rule=Host(`${WEB_HOST}`)"
        - "traefik.http.routers.odoo.entrypoints=websecure"
        - "traefik.http.routers.odoo.tls.certresolver=le"
        - "traefik.http.services.odoo.loadbalancer.server.port=${WEB_PORT}"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true

volumes:
  DB_VOLUME:
    external: true
    name: DB_VOLUME_${CLIENT_NAME}
  ODOO_VOLUME_NAME:
    external: true
    name: ODOO_VOLUME_${CLIENT_NAME}
  ODOO_CONFIG_VOLUME_NAME:
    external: true
    name: ODOO_CONFIG_VOLUME_${CLIENT_NAME}
  ODOO_ADDONS_VOLUME_NAME:
    external: true
    name: ODOO_ADDONS_VOLUME_${CLIENT_NAME}
  ODOO_ENTERPRISE_ADDONS_VOLUME_NAME:
    external: true
    name: ODOO_ENTERPRISE_ADDONS_VOLUME_${CLIENT_NAME}
  INIT_SCRIPT_VOLUME:
    external: true
    name: INIT_SCRIPT_VOLUME_${CLIENT_NAME}
  INIT_DB_SQL_VOLUME:
    external: true
    name: INIT_DB_SQL_VOLUME_${CLIENT_NAME}
