version: '3'
services:
  odoo:
    platform: linux/x86_64
    container_name: ${WEB_HOST}
    build: ${WEB_BUILD}
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-enterprise:/mnt/enterprise-addons
      - ${WEB_BUILD}/init-script.sh:/init-script.sh
      - ${WEB_BUILD}/init-db.sql:/init-db.sql
    user: root
    entrypoint: ["/bin/sh", "-c", "chmod +x /init-script.sh && /init-script.sh"]
    restart: always
  db:
    platform: linux/x86_64
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo-db-data:
  odoo-data:
