version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./${CLIENT_NAME}/pgdata:/var/lib/postgresql/data/pgdata
    networks:
      agent_network:
        aliases:
          - ${DB_HOST}
      traefik_public:
        aliases:
          - ${DB_HOST}

  odoo:
    image: odoo:16.0-20250311
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./${CLIENT_NAME}/odoo:/var/lib/odoo
      - ./${CLIENT_NAME}/config:/etc/odoo
      - ./${CLIENT_NAME}/addons:/mnt/extra-addons
      - ./${WEB_BUILD}/addons-enterprise:/mnt/enterprise-addons
    user: root
    entrypoint: ["/bin/sh", "-c", "cp /init-script.sh /tmp/init-script.sh && chmod +x /tmp/init-script.sh && /tmp/init-script.sh"]
    configs:
      - source: init_script
        target: /init-script.sh
      - source: init_db_sql
        target: /init-db.sql
    networks:
      - agent_network
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.odoo.rule=Host(`${WEB_HOST}`)"
        - "traefik.http.routers.odoo.entrypoints=websecure"
        - "traefik.http.routers.odoo.tls.certresolver=le"
        - "traefik.http.services.odoo.loadbalancer.server.port=${WEB_PORT}"

networks:
  traefik_public:
    external: true
    attachable: true
  agent_network:
    external: true

configs:
  init_script:
    file: ./${WEB_BUILD}/init-script.sh
  init_db_sql:
    file: ./${WEB_BUILD}/init-db.sql