[options]
addons_path = /mnt/extra-addons,/mnt/enterprise-addons
data_dir = /var/lib/odoo
web_build = ./16.0
web_host = odoo16
web_port = 8069
db_image = postgres
db_tag = 13
db_host = db16
db_port = 5432
db_name = postgres
db_user = odoo16
db_password = odoo16
expiration_date = '2027-02-22 00:00:00'
enterprise_code = 'm22112861297726'
admin_passwd = $pbkdf2-sha512$25000$2nspwrgjbkdueo.r0nopwq$o/icaehhw.hviqgnx9icgnrf5iuz2axt5wgtxozqg0jlfiooujodik4uuc00d9y8rfq3b.yg6u2y/xau6ogtxq
csv_internal_sep = ,
db_maxconn = 64
db_sslmode = prefer
http_enable = true
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 1000
limit_time_real = 1200
log_level = debug
proxy_mode = true
server_wide_modules = web
